### ISSUE TITLE
FileNotFoundException: java.io.FileNotFoundException: snowplow_bigquery_refresh_token.properties (No such file or directory)

### ISSUE THREAD

**Issue by jbthummar** [snowplow/bigquery-loader-cli#21]
I am running this command : 
./bigquery-loader-cli-0.1.0 --create-table "moonshot-1349" "dataset_test_1"  "table_test_1" part-00000.gzip
It's throwing following error:
FileNotFoundException: java.io.FileNotFoundException: snowplow_bigquery_refresh_token.properties (No such file or directory)
Exception in thread "main" java.lang.NullPointerException
    at com.snowplowanalytics.snowplow.bigquery.loader.BigqueryInterface.getCredentials(BigqueryInterface.scala:155)
    at com.snowplowanalytics.snowplow.bigquery.loader.BigqueryInterface.loadCredentials(BigqueryInterface.scala:135)
    at com.snowplowanalytics.snowplow.bigquery.loader.BigqueryInterface.<init>(BigqueryInterface.scala:110)
    at com.snowplowanalytics.snowplow.bigquery.loader.BigqueryLoaderCli$.main(BigqueryLoaderCli.scala:71)
    at com.snowplowanalytics.snowplow.bigquery.loader.BigqueryLoaderCli.main(BigqueryLoaderCli.scala)

Is there something I am missing?

**Comment by alexanderdean** [comment]
Hey @jbthummar - the code in question is from an R&D spike from 18 months ago - it's not something we're actively maintaining or supporting. Of course you're welcome to post your question to our Discourse forum on the offchance someone in the community is using this code.
